# Generated by Django 4.2.16 on 2024-09-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
    ]
